// These literal cues identify the requested interpretation, not arbitrary quoted prose.
// A missing cue stays missing. Admins still resolve context, negation and ambiguous metrics.
export const meaningCues = [
  'target',
  'Target',
  'TARGET',
  'goal',
  'Goal',
  'result',
  'Result',
  'actual',
  'Actual',
  'annual',
  'Annual',
  'annually',
  'Annually',
  'cumulative',
  'Cumulative',
  'estimate',
  'Estimate',
  'estimated',
  'Estimated',
  '目标',
  '結果',
  '结果',
  '年度',
  '累计',
  '累計',
  '估计',
  '估計',
  'sasaran',
  'Sasaran',
  'hasil',
  'Hasil',
  'tahunan',
  'Tahunan',
  'kumulatif',
  'Kumulatif',
  'anggaran',
  'Anggaran',
  'இலக்கு',
  'முடிவு',
  'வருடாந்திர',
  'ஒட்டுமொத்த',
  'மதிப்பீடு',
] as const;
